/**
 * Build-time reader for the ask-embeddings bundle feed (#329). Parallel to askIndex.ts:
 * reads the precomputed all-MiniLM-L6-v2 document vectors generated by `bosc export`
 * and returns them for the `/ask-embeddings.json` static asset. Returns an empty array
 * when the feed is absent (offline / fast-mode builds) — the Worker degrades to
 * BM25-only retrieval in that case.
 */
import { hasFeed, loadFeed } from "./bundle";
import type { EmbeddingEntry } from "@fn/api/_lib/retrieval";

export function buildAskEmbeddingsIndex(): EmbeddingEntry[] {
  if (!hasFeed("ask-embeddings")) return [];
  return loadFeed<EmbeddingEntry[]>("ask-embeddings");
}
