"""Render the hydrology findings as an evidence-tagged markdown dossier section.

Composes the three Tier-0 analyses — the water-balance + low-flow screen, the
pre/post stormwater runoff, and the baseline-vs-buildout scenario — into one
regenerable markdown document (``docs/HYDROLOGY.md``). Each figure keeps its
provenance tag so the dossier is auditable: ``[verified]`` for document/connector
values, ``[inference]`` for assumptions/derived.
"""

from __future__ import annotations

from bosc.config import Settings, get_settings
from bosc.hydrology.model import ProvenancedValue
from bosc.pipeline import hydrology as hydro_stage

_TAG = {
    "document": "verified",
    "connector": "verified",
    "assumption": "inference",
    "derived": "inference",
}


def _ev(pv: ProvenancedValue | None) -> str:
    if pv is None:
        return "—"
    return f"{pv.value:,.2f} {pv.unit} `[{_TAG[pv.source]}: {pv.source}]`"


def render_report(*, settings: Settings | None = None, live: bool = False) -> str:
    """Build the full hydrology markdown dossier (offline-deterministic by default)."""
    settings = settings or get_settings()
    balance, assim, _findings = hydro_stage.run_baseline(settings=settings, live=live)
    runoff, storm_findings = hydro_stage.run_storm(settings=settings, live=live)
    base, build, delta = hydro_stage.run_scenarios(settings=settings, live=live)

    out: list[str] = []
    w = out.append
    w("# Hydrology — Tier-0 municipal water-flow findings\n")
    w(
        "> Generated by `bosc` (`bosc.hydrology`). Tier-0 SCS screening — auditable and\n"
        "> fast, not a substitute for SWMM/HEC-RAS. Every figure is tagged `[verified]`\n"
        "> (read from a record or a live gauge) or `[inference]` (assumption/derived).\n"
    )

    w("\n## 1. The municipal loop and its low-flow squeeze\n")
    w("The Lima system is one closed loop on two rivers:\n")
    w("> Auglaize/Ottawa → Lima WTP → municipal + data-center demand → WWTPs → Ottawa River\n")
    w("\n| node | role | flow | receiving |")
    w("|---|---|---|---|")
    for n in balance.nodes:
        flow = n.return_flow or n.inflow
        w(f"| {n.node.name} | {n.node.role} | {_ev(flow)} | {n.node.receiving_water or '—'} |")
    w("\n**Low-flow assimilative screen** (discharge vs the receiving stream's cited 7Q10):\n")
    for c in assim:
        mark = "❌" if c.flag == "violation" else ("⚠️" if c.flag == "tight" else "✅")
        w(
            f"- {mark} **{c.discharger} → {c.receiving_water}**: 7Q10 "
            f"{c.design_low_flow.value:g} cfs vs discharge {c.discharge.value:.2f} cfs "
            f"→ {c.dilution_ratio:.2f}:1 dilution ({c.flag}). "
            f"`[{_TAG[c.design_low_flow.source]}]` {c.design_low_flow.citation}"
        )
    w(
        "\nAt design low flow the receiving streams carry less than the effluent they\n"
        "receive — the discharges are effectively undiluted.\n"
    )

    from bosc.hydrology.floodplain import load_wwtp_floodzones

    wf = load_wwtp_floodzones(settings=settings)
    if wf is not None and wf.plants:
        sited = [p for p in wf.plants if p.in_sfha]
        adjacent = [p for p in wf.plants if not p.in_sfha and p.nearest_buffer(contains="AE")]
        lead = (
            "All three plant sites sit in the FEMA floodplain"
            if len(sited) == len(wf.plants)
            else (
                f"None of the {len(wf.plants)} plant sites sits in the FEMA Special Flood "
                "Hazard Area at its ECHO-reported point"
                if not sited
                else f"{len(sited)} of {len(wf.plants)} plant sites sit in the FEMA SFHA"
            )
        )
        w(
            f"\n**Outfall flood exposure.** {lead}, but the discharge infrastructure is "
            f"flood-adjacent on streams already shown to be undiluted at low flow "
            f"`[verified: document]`:\n"
        )
        w("\n| Plant | Receiving water | In SFHA | Nearest AE | Nearest floodway |")
        w("|---|---|---|---|---|")
        for p in wf.plants:
            ae = p.nearest_buffer(contains="AE")
            fw = p.nearest_buffer(contains="FLOODWAY")
            w(
                f"| {p.name} | {p.receiving_water or '—'} | {'yes' if p.in_sfha else 'no'} "
                f"| {f'≤{ae} m' if ae else '—'} | {f'≤{fw} m' if fw else '—'} |"
            )
        if adjacent:
            w(
                f"\n{wf.note} So the mapped exposure understates the outfalls': the "
                "discharge points themselves sit at the receiving water, inside or at the "
                "edge of the AE floodplain.\n"
            )

    from bosc.hydrology.maumee import load_maumee_tmdl

    tmdl = load_maumee_tmdl(settings=settings)
    if tmdl is not None and tmdl.facilities:
        w("\n## 2. The Maumee Nutrient TMDL: the same discharges are capped phosphorus loads\n")
        w(
            "These discharges don't just strain a local stream. The Ottawa flows to the\n"
            "Auglaize and on to the **Maumee** — Lake Erie's largest tributary and the\n"
            "driver of its western-basin harmful algal blooms. The 2023 Maumee Watershed\n"
            "Nutrient TMDL (Ohio EPA, US-EPA-approved) assigns each individually permitted\n"
            "discharger a total-phosphorus **wasteload allocation**: a spring-season\n"
            "(March-July) cap, also stated as a daily equivalent. The plants the low-flow\n"
            "screen flags as effectively undiluted are the same permits carrying these caps\n"
            "`[verified: document]`:\n"
        )
        w("\n| facility | NPDES | spring TP (metric tons) | daily TP (kg) |")
        w("|---|---|---|---|")
        for fac in tmdl.facilities:
            w(
                f"| {fac.facility} | {fac.npdes or '—'} | "
                f"{fac.spring_tp.value:g} | {fac.daily_tp.value:g} |"
            )
        if tmdl.grouped_spring_tp is not None and tmdl.grouped_daily_tp is not None:
            w(
                f"\nAcross the whole grouped category of individually permitted dischargers the\n"
                f"cap totals **{tmdl.grouped_spring_tp.value:g} metric tons** "
                f"({tmdl.grouped_daily_tp.value:g} kg/day) of spring phosphorus. So the local\n"
                f"dilution failure compounds a basin-scale constraint: at design low flow these\n"
                f"effluents are near-undiluted, and every pound of phosphorus is metered against a\n"
                f"Lake Erie nutrient budget.\n"
            )

    w("\n## 3. Stormwater: paving the corridor\n")

    from bosc.hydrology.climate import load_climatology

    clim = load_climatology(settings=settings)
    if clim is not None:
        ann = clim.annual_precip_mm()
        wettest = clim.wettest_month()
        t2m = clim.get("T2M")
        if ann is not None and wettest is not None and t2m is not None:
            w(
                f"**Climate baseline (NASA POWER).** The Lima point averages "
                f"**~{ann:,.0f} mm/yr** of precipitation (corrected), peaking in "
                f"{wettest[0].title()}, at a mean annual temperature of "
                f"**{t2m.annual:.1f} °C** `[reference: NASA POWER climatology]`. The "
                f"satellite climate *normal* sets the long-run water budget; the design "
                f"storm below is the NOAA Atlas-14 *extreme* the corridor must detain — "
                f"the two are complementary.\n"
            )
            from bosc.hydrology.et import penman_monteith_et0

            try:
                et0 = penman_monteith_et0(clim)
            except ValueError:
                et0 = None
            if et0 is not None:
                net = ann - et0.annual_mm
                precip_m = clim.get("PRECTOTCORR")
                deficit = (
                    [m for m in et0.monthly_mm_day if et0.monthly_mm_day[m] > precip_m.monthly[m]]
                    if precip_m is not None
                    else []
                )
                span = f"{deficit[0].title()}-{deficit[-1].title()}" if deficit else "none"
                w(
                    f"\n**Reference ET (FAO-56 Penman-Monteith).** Atmospheric water "
                    f"*demand* runs **~{et0.annual_mm:,.0f} mm/yr** of reference ET0, "
                    f"computed from the same POWER normals (temperature, humidity, wind, "
                    f"solar) `[derived: FAO-56 Penman-Monteith]`. Net of precipitation "
                    f"that is **{net:+,.0f} mm/yr** — and ET0 *exceeds* rainfall across "
                    f"the **{span}** growing season, so summer soil moisture, pond "
                    f"evaporation, and any consumptive cooling draw compete for water in "
                    f"the months the Ottawa is already near its low-flow floor (§4).\n"
                )

    w(
        f"A {runoff.storm.return_period_yr}-yr 24-hr design storm "
        f"({_ev(runoff.storm.depth)}) over the {runoff.area.value:,.0f}-ac footprint "
        f"`[{_TAG[runoff.area.source]}]`:\n"
    )
    w("\n| case | curve number | peak (cfs) | volume (ac-ft) |")
    w("|---|---|---|---|")
    w(
        f"| pre-development (cropland) | {runoff.pre.curve_number:.0f} | {runoff.pre.peak_cfs:,.0f} | {runoff.pre.volume_acft:,.0f} |"
    )
    w(
        f"| post-development (impervious) | {runoff.post.curve_number:.0f} | {runoff.post.peak_cfs:,.0f} | {runoff.post.volume_acft:,.0f} |"
    )
    for f in storm_findings:
        w(f"\n- {f.detail}")

    from bosc.hydrology.floodplain import load_campus_floodzone

    cf = load_campus_floodzone(settings=settings)
    if cf is not None:
        if cf.in_floodplain:
            w(
                f"\n\n**Part of the footprint lies in the FEMA floodplain.** The recorded\n"
                f"campus parcels intersect FEMA Special Flood Hazard Area "
                f"({', '.join(cf.in_parcels_zones)}; DFIRM {cf.firm}) `[verified: document]` —\n"
                f"development there faces base-flood-elevation and floodway constraints.\n"
            )
        elif cf.nearby_zones:
            w(
                f"\n\n**The footprint sits just outside the FEMA floodplain — but only just.**\n"
                f"The recorded campus parcels intersect no FEMA Special Flood Hazard Area, yet\n"
                f"Zone {' and '.join(cf.nearby_zones)} (1%-annual-chance floodplain and regulatory\n"
                f"floodway) reach within ~{cf.nearby_buffer_m} m of them (FEMA DFIRM {cf.firm})\n"
                f"`[verified: document]`. The post-development runoff increase routes toward that\n"
                f"corridor; a regulatory floodway tolerates no rise, so added peak discharge there\n"
                f"is a permitting constraint, not only a detention-sizing question.\n"
            )

    w("\n\n## 4. Scenario: data-center cooling vs the Ottawa's low flow\n")
    basis = build.scenario.basis
    if basis is not None:
        w("The cooling demand is **sourced**, derived from disclosed campus data by two methods:\n")
        w(
            f"- top-down: IT load {_ev(basis.it_load)} x WUE {_ev(basis.wue)} → "
            f"**{basis.consumptive_low.value:g} MGD** consumptive\n"
            f"- bottom-up: FM-2 blowdown x {basis.cycles_of_concentration.value:g} cycles → "
            f"**{basis.consumptive_high.value:g} MGD** consumptive (upper bound)\n"
        )
        w(
            f"\nThey bracket the consumptive demand at "
            f"**{basis.consumptive_low.value:g}-{basis.consumptive_high.value:g} MGD** "
            f"(FM-2 is not purely cooling blowdown). The conclusion is robust to the range.\n"
        )
    w("\n| scenario | cooling intake | consumptive fraction | net basin loss |")
    w("|---|---|---|---|")
    for r in (base, build):
        w(
            f"| {r.scenario.name} | {r.scenario.cooling_demand.value:g} MGD | "
            f"{r.scenario.consumptive_fraction.value:g} | {_ev(r.consumptive_loss)} |"
        )
    if delta.multiple_of_7q10 is not None:
        w(
            f"\nBuildout adds **{delta.consumptive_increase_cfs:,.2f} cfs** of net consumptive "
            f"draw — **{delta.multiple_of_7q10:g}x** the Ottawa River's cited 7Q10 "
            f"({delta.ottawa_7q10_cfs:g} cfs). At design low flow the Ottawa nearly dries "
            f"(1Q10 = 0 cfs); a data center's cooling draw competes for water the river\n"
            f"does not have — even the low estimate is tens of times the 7Q10.\n"
        )
    w("\n\n## 5. Tier-1 escalation (EPA SWMM)\n")
    w(
        "`bosc tier1` runs the real EPA SWMM5 engine on the footprint under the design\n"
        "storm for two questions Tier-0 only approximates: the **detention volume** that\n"
        "holds the post-development peak to the pre-development rate, and the **sanitary\n"
        "wet-weather surcharge** (dry-weather base + RDII) against each plant's documented\n"
        "wet-weather headroom. Hydraulic routing parameters (imperviousness, RDII, basin\n"
        "geometry) are assumptions; the footprint, storm, and plant design flows stay\n"
        "document/connector-sourced. Engine-dependent, so its figures live in the live command.\n"
    )
    from bosc.hydrology.sanitary import load_sanitary_basis

    san = load_sanitary_basis(settings=settings)
    if san is not None and san.decree_note:
        rows = "; ".join(
            f"{p.plant} {p.avg_design_flow.value:g}/{p.peak_capacity.value:g} MGD "
            f"(headroom {p.headroom_mgd:g})"
            for p in san.plants
            if p.peak_capacity is not None and p.headroom_mgd is not None
        )
        w(
            f"\n**The surcharge lands on a system with no headroom to give.** Permitted\n"
            f"average / peak design flows are document-cited [verified]: {rows}. The decisive\n"
            f"fact is regulatory: the collection system is already under a **2005 OEPA mandate\n"
            f"to eliminate all SSO bypassing by 2015**, with **${san.ii_remediation_musd.value:g}M**\n"
            f"of storm-water I/I remediation and a 21-inch trunk replaced by 48-inch purely to\n"
            f"equalize wet-weather I/I. So each plant's nominal wet-weather headroom (peak minus\n"
            f"permitted average) is already documented as effectively spent before the campus\n"
            f"adds load. The campus's documented dry-weather contribution is the {san.campus_industrial.value:g}\n"
            f"MGD FM-2 industrial discharge; the storm RDII multiplier on top remains an assumption.\n"
        )
    from bosc.hydrology.stormplan import load_inventory

    inv = load_inventory(settings=settings)
    if inv is not None and not inv.detention_shown:
        w(
            f"\n**Detention is the absent control, not a modeled redesign.** The campus\n"
            f"grading & stormwater plan (`{inv.sheet_id}`, {inv.phase}, "
            f"{'[verified]' if inv.rim_min.verified else '[inference]'}) routes runoff via\n"
            f"catch basins -> inlets -> storm sewer to headwall outfalls (with rock check dams\n"
            f"and overland flood routing) and shows **no detention, retention, or infiltration\n"
            f"storage** across its {inv.rim_labels} storm-structure rims "
            f"({inv.rim_min.value:.0f}-{inv.rim_max.value:.0f} ft). So the SWMM-sized basin is the\n"
            f"on-site control the as-drawn 95% design omits. Pipe connectivity/inverts are drawn\n"
            f"as vector geometry with no schedule table, so a routable network is deliberately\n"
            f"not transcribed (omission over invention).\n"
        )
    w("\n---\n")
    w(
        "_Sources: USGS NWIS (streamflow), NOAA Atlas-14 (design rainfall), NASA POWER\n"
        "(climate normals), Ohio EPA NPDES fact sheets 2PH00006 / 2PH00007 / 2IG00001\n"
        "(receiving-stream 7Q10), Maumee Watershed Nutrient TMDL Appendix 4 (phosphorus\n"
        "WLAs), recorded Bistrozzi parcels (footprint). Regenerate with `bosc hydro-report --write`._\n"
    )
    return "\n".join(out)


def write_report(*, settings: Settings | None = None, live: bool = False) -> str:
    """Write the dossier to ``docs/HYDROLOGY.md`` and return the path."""
    settings = settings or get_settings()
    from pathlib import Path

    path = Path(__file__).resolve().parents[3] / "docs" / "HYDROLOGY.md"
    path.write_text(render_report(settings=settings, live=live), encoding="utf-8")
    return str(path)
