"""Render the hydrology findings as an evidence-tagged markdown dossier section.

Composes the three Tier-0 analyses — the water-balance + low-flow screen, the
pre/post stormwater runoff, and the baseline-vs-buildout scenario — into one
regenerable markdown document (``docs/HYDROLOGY.md``). Each figure keeps its
provenance tag so the dossier is auditable: ``[verified]`` for document/connector
values, ``[inference]`` for assumptions/derived.
"""

from __future__ import annotations

from bosc.config import Settings, get_settings
from bosc.hydrology.model import ProvenancedValue
from bosc.pipeline import hydrology as hydro_stage

_TAG = {
    "document": "verified",
    "connector": "verified",
    "assumption": "inference",
    "derived": "inference",
}


def _ev(pv: ProvenancedValue | None) -> str:
    if pv is None:
        return "—"
    return f"{pv.value:,.2f} {pv.unit} `[{_TAG[pv.source]}: {pv.source}]`"


def render_report(*, settings: Settings | None = None, live: bool = False) -> str:
    """Build the full hydrology markdown dossier (offline-deterministic by default)."""
    settings = settings or get_settings()
    balance, assim, _findings = hydro_stage.run_baseline(settings=settings, live=live)
    runoff, storm_findings = hydro_stage.run_storm(settings=settings, live=live)
    base, build, delta = hydro_stage.run_scenarios(settings=settings, live=live)

    out: list[str] = []
    w = out.append
    w("# Hydrology — Tier-0 municipal water-flow findings\n")
    w(
        "> Generated by `bosc` (`bosc.hydrology`). Tier-0 SCS screening — auditable and\n"
        "> fast, not a substitute for SWMM/HEC-RAS. Every figure is tagged `[verified]`\n"
        "> (read from a record or a live gauge) or `[inference]` (assumption/derived).\n"
    )

    w("\n## 1. The municipal loop and its low-flow squeeze\n")
    w("The Lima system is one closed loop on two rivers:\n")
    w("> Auglaize/Ottawa → Lima WTP → municipal + data-center demand → WWTPs → Ottawa River\n")
    w("\n| node | role | flow | receiving |")
    w("|---|---|---|---|")
    for n in balance.nodes:
        flow = n.return_flow or n.inflow
        w(f"| {n.node.name} | {n.node.role} | {_ev(flow)} | {n.node.receiving_water or '—'} |")
    w("\n**Low-flow assimilative screen** (discharge vs the receiving stream's cited 7Q10):\n")
    for c in assim:
        mark = "❌" if c.flag == "violation" else ("⚠️" if c.flag == "tight" else "✅")
        w(
            f"- {mark} **{c.discharger} → {c.receiving_water}**: 7Q10 "
            f"{c.design_low_flow.value:g} cfs vs discharge {c.discharge.value:.2f} cfs "
            f"→ {c.dilution_ratio:.2f}:1 dilution ({c.flag}). "
            f"`[{_TAG[c.design_low_flow.source]}]` {c.design_low_flow.citation}"
        )
    w(
        "\nAt design low flow the receiving streams carry less than the effluent they\n"
        "receive — the discharges are effectively undiluted.\n"
    )

    w("\n## 2. Stormwater: paving the corridor\n")
    w(
        f"A {runoff.storm.return_period_yr}-yr 24-hr design storm "
        f"({_ev(runoff.storm.depth)}) over the {runoff.area.value:,.0f}-ac footprint "
        f"`[{_TAG[runoff.area.source]}]`:\n"
    )
    w("\n| case | curve number | peak (cfs) | volume (ac-ft) |")
    w("|---|---|---|---|")
    w(
        f"| pre-development (cropland) | {runoff.pre.curve_number:.0f} | {runoff.pre.peak_cfs:,.0f} | {runoff.pre.volume_acft:,.0f} |"
    )
    w(
        f"| post-development (impervious) | {runoff.post.curve_number:.0f} | {runoff.post.peak_cfs:,.0f} | {runoff.post.volume_acft:,.0f} |"
    )
    for f in storm_findings:
        w(f"\n- {f.detail}")

    w("\n\n## 3. Scenario: data-center cooling vs the Ottawa's low flow\n")
    basis = build.scenario.basis
    if basis is not None:
        w("The cooling demand is **sourced**, derived from disclosed campus data by two methods:\n")
        w(
            f"- top-down: IT load {_ev(basis.it_load)} x WUE {_ev(basis.wue)} → "
            f"**{basis.consumptive_low.value:g} MGD** consumptive\n"
            f"- bottom-up: FM-2 blowdown x {basis.cycles_of_concentration.value:g} cycles → "
            f"**{basis.consumptive_high.value:g} MGD** consumptive (upper bound)\n"
        )
        w(
            f"\nThey bracket the consumptive demand at "
            f"**{basis.consumptive_low.value:g}-{basis.consumptive_high.value:g} MGD** "
            f"(FM-2 is not purely cooling blowdown). The conclusion is robust to the range.\n"
        )
    w("\n| scenario | cooling intake | consumptive fraction | net basin loss |")
    w("|---|---|---|---|")
    for r in (base, build):
        w(
            f"| {r.scenario.name} | {r.scenario.cooling_demand.value:g} MGD | "
            f"{r.scenario.consumptive_fraction.value:g} | {_ev(r.consumptive_loss)} |"
        )
    if delta.multiple_of_7q10 is not None:
        w(
            f"\nBuildout adds **{delta.consumptive_increase_cfs:,.2f} cfs** of net consumptive "
            f"draw — **{delta.multiple_of_7q10:g}x** the Ottawa River's cited 7Q10 "
            f"({delta.ottawa_7q10_cfs:g} cfs). At design low flow the Ottawa nearly dries "
            f"(1Q10 = 0 cfs); a data center's cooling draw competes for water the river\n"
            f"does not have — even the low estimate is tens of times the 7Q10.\n"
        )
    w("\n---\n")
    w(
        "_Sources: USGS NWIS (streamflow), NOAA Atlas-14 (design rainfall), Ohio EPA NPDES\n"
        "fact sheets 2PH00006 / 2PH00007 / 2IG00001 (receiving-stream 7Q10), recorded\n"
        "Bistrozzi parcels (footprint). Regenerate with `bosc hydro-report --write`._\n"
    )
    return "\n".join(out)


def write_report(*, settings: Settings | None = None, live: bool = False) -> str:
    """Write the dossier to ``docs/HYDROLOGY.md`` and return the path."""
    settings = settings or get_settings()
    from pathlib import Path

    path = Path(__file__).resolve().parents[3] / "docs" / "HYDROLOGY.md"
    path.write_text(render_report(settings=settings, live=live), encoding="utf-8")
    return str(path)
