"""``bosc catalog render`` — generate the ``data/reference`` README facts from the catalog.

Phase 2 of the data-catalog epic (#631, issue #627). Makes the catalog the single source of
truth for each reference collection's *facts* — the files, the producing ``bosc`` command, the
source, license, access tier, and refresh cadence — and kills the prose drift of 40
hand-maintained READMEs (only a few of which state a license today).

**Additive + prose-preserving.** Render injects a marker-delimited *generated block*
(``<!-- catalog:begin -->`` … ``<!-- catalog:end -->``) at the end of a collection's
``README.md`` and **preserves everything else verbatim** — the curated narrative survives
untouched. A collection opts in the first time it is rendered; from then on
:func:`watermark.catalog_check.check` re-derives the block and fails on drift (``render-drift``),
so a rendered README can't silently fall out of sync with the catalog. Collections without the
marker are left alone (they opt in as their entries are reviewed).
"""

from __future__ import annotations

from collections import defaultdict
from typing import Literal

from pydantic import BaseModel, ConfigDict

from watermark.catalog import CatalogEntry, entries_for_scope
from watermark.config import Settings, get_settings

BEGIN = "<!-- catalog:begin (generated by `bosc catalog render`; do not edit inside) -->"
END = "<!-- catalog:end -->"


def reference_collections(*, settings: Settings | None = None) -> dict[str, list[CatalogEntry]]:
    """Reference-scope entries grouped by collection (the first dir under ``reference/``)."""
    settings = settings or get_settings()
    groups: dict[str, list[CatalogEntry]] = defaultdict(list)
    for entry in entries_for_scope("reference", settings=settings):
        if not entry.storage:
            continue
        collection = entry.storage[0].relpath.split("/")[1]
        groups[collection].append(entry)
    return dict(groups)


def render_block(entries: list[CatalogEntry]) -> str:
    """The generated markdown block for a collection's entries (markdownlint-clean)."""
    lines: list[str] = [
        BEGIN,
        "",
        "**Cataloged datasets** — generated from `data/catalog/reference/`; "
        "run `bosc catalog render --apply` after editing an entry.",
    ]
    for entry in sorted(entries, key=lambda e: e.id):
        meta = (
            f"Source: {entry.producer.source} · License: {entry.license or 'unspecified'} · "
            f"Access: {entry.access_tier} · Site scope: {entry.site_scope} · "
            f"Refresh: {entry.refresh.cadence}"
        )
        if entry.refresh.ttl_days:
            meta += f" (ttl {entry.refresh.ttl_days}d)"
        if entry.refresh.last_refreshed:
            meta += f", last {entry.refresh.last_refreshed}"
        lines += ["", f"### `{entry.id}` — {entry.title}", "", meta]
        if entry.producer.command:
            lines += ["", f"Regenerate: `bosc {entry.producer.command}`"]
        if entry.storage:
            lines += ["", "| file | type | lfs |", "| --- | --- | --- |"]
            for item in entry.storage:
                lines.append(
                    f"| `{item.relpath}` | {item.media_type} | {'yes' if item.lfs else 'no'} |"
                )
    lines += ["", END]
    return "\n".join(lines)


def has_block(text: str) -> bool:
    return BEGIN in text and END in text


def splice_block(existing: str, block: str) -> str:
    """Append/replace the generated block at the end of ``existing``, preserving all prose."""
    prose = (existing[: existing.index(BEGIN)] if has_block(existing) else existing).rstrip("\n")
    return f"{prose}\n\n{block}\n" if prose else f"{block}\n"


class RenderAction(BaseModel):
    """One render outcome for a reference collection (surfaced by the CLI)."""

    model_config = ConfigDict(extra="forbid")

    collection: str
    action: Literal["added", "updated", "unchanged", "no-readme"]
    relpath: str


def render(
    *,
    settings: Settings | None = None,
    only: str | None = None,
    apply: bool = False,
) -> list[RenderAction]:
    """Render the generated block into each reference collection's README (writes when ``apply``).

    ``only`` restricts to a single collection. A collection whose ``README.md`` is missing is
    reported as ``no-readme`` and skipped (render is additive — it never invents a whole file).
    """
    settings = settings or get_settings()
    actions: list[RenderAction] = []
    for collection, entries in sorted(reference_collections(settings=settings).items()):
        if only and collection != only:
            continue
        readme = settings.reference_dir / collection / "README.md"
        relpath = str(readme.relative_to(settings.data_dir))
        if not readme.exists():
            actions.append(RenderAction(collection=collection, action="no-readme", relpath=relpath))
            continue
        existing = readme.read_text(encoding="utf-8")
        rendered = splice_block(existing, render_block(entries))
        if rendered == existing:
            actions.append(RenderAction(collection=collection, action="unchanged", relpath=relpath))
            continue
        action: Literal["added", "updated"] = "updated" if has_block(existing) else "added"
        if apply:
            readme.write_text(rendered, encoding="utf-8")
        actions.append(RenderAction(collection=collection, action=action, relpath=relpath))
    return actions


def render_drift(*, settings: Settings | None = None) -> list[tuple[str, str]]:
    """Collections whose committed README has the marker but no longer matches ``render``.

    Returns ``(collection, relpath)`` pairs. Self-limiting: a README without the generated
    marker has not opted in and is never flagged — so the gate grows as collections are rendered.
    """
    settings = settings or get_settings()
    drifted: list[tuple[str, str]] = []
    for collection, entries in sorted(reference_collections(settings=settings).items()):
        readme = settings.reference_dir / collection / "README.md"
        if not readme.exists():
            continue
        existing = readme.read_text(encoding="utf-8")
        if not has_block(existing):
            continue  # opt-in: un-rendered READMEs are not gated
        if splice_block(existing, render_block(entries)) != existing:
            drifted.append((collection, str(readme.relative_to(settings.data_dir))))
    return drifted
