"""Render the localized economic baseline as a site page.

Generated from the committed ``data/reference/economics/baseline.yaml`` (BLS QCEW),
not a live pull — so the static build needs no network. Surfaces Allen County's
employment trend and industry mix, and reads the BLS location quotients as the
county's export-orientation (the proxy for an import/export ratio).
"""

from __future__ import annotations

from bosc.economics.model import EconomicBaseline, SectorEmployment

# Location-quotient bands: >1 means the sector is over-represented locally (exports
# beyond local demand); <1 means under-represented (net "imported" from elsewhere).
_LQ_STRONG = 1.2
_LQ_WEAK = 0.8


def _lq(sector: SectorEmployment) -> float | None:
    return sector.location_quotient.value if sector.location_quotient else None


def _export_orientation(lq: float | None) -> str:
    if lq is None:
        return "—"
    if lq >= _LQ_STRONG:
        return f"**{lq:.2f}** · export-oriented"
    if lq <= _LQ_WEAK:
        return f"{lq:.2f} · under-represented"
    return f"{lq:.2f} · local-serving"


def _population_section(baseline: EconomicBaseline) -> list[str]:
    """Population-over-time table + trend line, or a one-line gap note when absent."""
    pop = baseline.population
    if pop is None or not pop.points:
        return [
            "*Population over time is not yet included — set `BOSC_CENSUS_API_KEY` and "
            "rerun `bosc economics`.*",
            "",
        ]
    lines = [
        "## Population over time",
        "",
        f"Total population, {pop.area_name} ({pop.source}).",
        "",
        "| Year | Population |",
        "|---|---|",
    ]
    for p in pop.points:
        lines.append(f"| {p.year} | {p.population.value:,.0f} |")
    lines.append("")
    first, last = pop.points[0], pop.points[-1]
    base = first.population.value
    delta = last.population.value - base
    pct = (delta / base * 100) if base else 0.0
    direction = "grew" if delta > 0 else "declined"
    lines += [
        f"Population **{direction} {abs(pct):.1f}%** "
        f"({base:,.0f} → {last.population.value:,.0f}) between {first.year} and "
        f"{last.year} — the demographic baseline a ~50-job campus joins.",
        "",
    ]
    return lines


def render_economics(baseline: EconomicBaseline) -> str:
    latest = baseline.latest
    lines = [
        "# Economics — localized baseline",
        "",
        f"What Allen County's economy actually is, quantitatively — the ground the "
        f"data-center deal sits on. Employment by industry for **{latest.year}** "
        "(BLS QCEW), with each sector's **location quotient**: its county employment "
        "share over the national share. A quotient above 1 means the county does more "
        "of that work than the nation — it *exports*; below 1 means it imports. (No "
        "clean county import/export series exists; the location quotient is the "
        "standard proxy.)",
        "",
        '!!! note "Source & discipline"',
        "    Figures are **BLS QCEW** (employment) and **US Census ACS 5-year** "
        "(population) — regenerated by `bosc economics`. Every number is "
        "connector-tagged `[verified]`. See the "
        "[reference README](data/reference/economics/README.md).",
        "",
        *_population_section(baseline),
        "## Employment trend",
        "",
        "| Year | Total covered employment |",
        "|---|---|",
    ]
    for pt in baseline.trend:
        lines.append(f"| {pt.year} | {pt.total_employment.value:,.0f} |")
    lines.append("")
    if len(baseline.trend) >= 2:
        first, last = baseline.trend[0], baseline.trend[-1]
        delta = last.total_employment.value - first.total_employment.value
        pct = (delta / first.total_employment.value * 100) if first.total_employment.value else 0.0
        direction = "grew" if delta > 0 else "shrank"
        lines += [
            f"Total covered employment **{direction} {abs(pct):.1f}%** "
            f"({first.total_employment.value:,.0f} → {last.total_employment.value:,.0f}) "
            f"between {first.year} and {last.year} — the labor base the campus's "
            f"~50 promised jobs join (see [Economics](docs/ECONOMICS.md)).",
            "",
        ]
    lines += [
        "## Industry mix & export-orientation",
        "",
        f"Private employment by NAICS sector, {latest.year}, ranked by jobs.",
        "",
        "| Sector | Jobs | Establishments | Location quotient |",
        "|---|---|---|---|",
    ]
    for s in latest.sectors:
        estabs = f"{s.establishments.value:,.0f}" if s.establishments else "—"
        lines.append(
            f"| {s.naics} · {s.sector_name} | {s.annual_avg_employment.value:,.0f} "
            f"| {estabs} | {_export_orientation(_lq(s))} |"
        )
    lines.append("")

    exporters = sorted(
        (s for s in latest.sectors if (_lq(s) or 0) >= _LQ_STRONG),
        key=lambda s: _lq(s) or 0,
        reverse=True,
    )
    if exporters:
        named = ", ".join(f"{s.sector_name} ({_lq(s):.2f})" for s in exporters)
        lines += [
            "### What the county exports",
            "",
            f"The export-oriented base (location quotient ≥ {_LQ_STRONG}): {named}. "
            "Allen County is an industrial/manufacturing economy — the relevant frame "
            "for whether a ~50-job, ~275 MW data center on a 75% abatement adds to that "
            "base or substitutes a low-employment land use onto it "
            "([Economics](docs/ECONOMICS.md), [the bigger picture](docs/bigger-picture.md)).",
            "",
        ]
    if baseline.note:
        lines += [f"*{baseline.note}*", ""]
    return "\n".join(lines)


def export_economics(baseline: EconomicBaseline) -> EconomicBaseline:
    """Export the localized economic baseline as a feed (it is already feed-ready).

    Every number on the baseline is a :class:`~bosc.economics.model.ProvenancedValue`
    (BLS QCEW / Census ACS), so the model already carries structured provenance per #60 —
    the feed is the model itself; this exporter gives the module a uniform surface (#59).
    """
    return baseline
