// Load the build-time ask-embeddings index for hybrid retrieval (#329).
// Parallel to askIndexLoad.ts; returns null when embeddings are absent so the
// caller degrades gracefully to BM25-only retrieval.

import { fetchWithTimeout } from "./http";
import type { EmbeddingEntry } from "./retrieval";

let loaded = false;
let cached: EmbeddingEntry[] | null = null;

/** Test seam: drop the isolate cache. */
export function _resetAskEmbeddingsCache(): void {
  loaded = false;
  cached = null;
}

/**
 * Load the precomputed ask-embeddings index. Returns null when:
 * - the asset is absent (404) — embeddings not yet generated by `bosc export`
 * - the array is empty — offline / fast-mode build without embedding generation
 *
 * In either case the caller degrades to BM25-only retrieval. Throws on non-404
 * fetch failures so misconfigured deploys surface immediately.
 */
export async function loadAskEmbeddings(
  requestUrl: string,
  embeddingsUrl?: string,
): Promise<EmbeddingEntry[] | null> {
  if (loaded) return cached;
  const url = embeddingsUrl ?? new URL("/ask-embeddings.json", requestUrl).toString();
  const res = await fetchWithTimeout(url);
  if (res.status === 404) {
    loaded = true;
    return null;
  }
  if (!res.ok) throw new Error(`ask-embeddings fetch failed: ${res.status}`);
  const entries = (await res.json()) as EmbeddingEntry[];
  cached = Array.isArray(entries) && entries.length > 0 ? entries : null;
  loaded = true;
  return cached;
}
