// Load the build-time ask-embeddings index for hybrid retrieval (#329).
// Parallel to askIndexLoad.ts; returns null when embeddings are absent so the
// caller degrades gracefully to BM25-only retrieval.

import { fetchWithTimeout } from "./http";
import type { EmbeddingEntry } from "./retrieval";

// Keyed by resolved URL so different embeddingsUrl values don't share a result.
// Stores the in-flight promise to deduplicate concurrent requests for the same URL.
const cache = new Map<string, Promise<EmbeddingEntry[] | null>>();

/** Test seam: drop the isolate cache. */
export function _resetAskEmbeddingsCache(): void {
  cache.clear();
}

async function _fetchEmbeddings(url: string): Promise<EmbeddingEntry[] | null> {
  const res = await fetchWithTimeout(url);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`ask-embeddings fetch failed: ${res.status}`);
  const entries = (await res.json()) as EmbeddingEntry[];
  return Array.isArray(entries) && entries.length > 0 ? entries : null;
}

/**
 * Load the precomputed ask-embeddings index. Returns null when:
 * - the asset is absent (404) — embeddings not yet generated by `bosc export`
 * - the array is empty — offline / fast-mode build without embedding generation
 *
 * In either case the caller degrades to BM25-only retrieval. Throws on non-404
 * fetch failures so misconfigured deploys surface immediately.
 */
export async function loadAskEmbeddings(
  requestUrl: string,
  embeddingsUrl?: string,
): Promise<EmbeddingEntry[] | null> {
  const url = embeddingsUrl ?? new URL("/ask-embeddings.json", requestUrl).toString();
  let inflight = cache.get(url);
  if (!inflight) {
    inflight = _fetchEmbeddings(url);
    cache.set(url, inflight);
  }
  return inflight;
}
