import type { APIRoute } from "astro";
import { buildAskEmbeddingsIndex } from "../lib/askEmbeddingsIndex";

// Static endpoint: emits `/ask-embeddings.json` at build time (#329). Parallel to
// `/ask-index.json`: one all-MiniLM-L6-v2 embedding per ask-unit (generated by
// `bosc export`, omitted with `--no-embeddings`), fetched by /api/ask for hybrid
// BM25 + vector retrieval. Returns an empty array for offline/fast builds — the Worker
// degrades to BM25-only.
export const GET: APIRoute = () =>
  new Response(JSON.stringify(buildAskEmbeddingsIndex()), {
    headers: { "content-type": "application/json; charset=utf-8" },
  });
