"""``watermark catalog audit`` — generate the corpus completeness audit from the catalog (#631 / #659).

Phase 3 of the data-catalog epic. The hand-maintained
``data/extracted/legal/corpus-completeness-audit.md`` distinguishes two kinds of gap:
**substantive** (records the county *withheld* — irreplaceable human analysis, kept as prose)
and **integrity** (existence / freshness checks the audit itself describes as "computed by
script"). This module automates that second half: a deterministic markdown report rendered
from the catalog (:mod:`watermark.catalog`) and the committed reconcile snapshot
(``data/catalog/_observed.yaml``).

It reads the *committed* snapshot — not a live observation — so the report is content-stable
and LFS-agnostic (it reflects what ``watermark catalog reconcile`` last recorded, exactly as the
checksum gate does). The generated file is ``data/catalog/COMPLETENESS.md``; like
``watermark catalog render``, drift is gated by :func:`watermark.catalog.check.check` so the committed
report can't silently fall out of sync with the snapshot.
"""

from __future__ import annotations

from collections import defaultdict

from pydantic import BaseModel, ConfigDict, Field

from watermark.catalog import CatalogEntry, load_entries
from watermark.catalog.reconcile import ObservedEntry, ObservedSnapshot, load_observed
from watermark.catalog.sites import _resolved_relpaths, is_relevant
from watermark.config import Settings, get_settings
from watermark.sites import SITES

AUDIT_RELPATH = "catalog/COMPLETENESS.md"
GENERATED = "<!-- generated by `bosc catalog audit --apply`; do not edit by hand -->"


def _collection(entry: CatalogEntry) -> str:
    """The dataset's collection — the first dir under its scope, ``{site}`` dropped."""
    if not entry.storage:
        return entry.scope
    parts = [p for p in entry.storage[0].relpath.split("/")[1:-1] if p != "{site}"]
    return parts[0] if parts else entry.scope


class DatasetState(BaseModel):
    """One dataset's integrity standing, reduced from its committed observed record."""

    model_config = ConfigDict(extra="forbid")

    id: str
    scope: str
    collection: str
    state: str  # present | stale | unmaterialized | missing | unobserved


def _state(obs: ObservedEntry | None) -> str:
    if obs is None:
        return "unobserved"
    if not obs.exists:
        return "missing"
    if not obs.lfs_materialized:
        return "unmaterialized"  # an LFS pointer in the snapshot — expected, not a gap
    if obs.stale:
        return "stale"
    return "present"


class CollectionAudit(BaseModel):
    """A collection's per-state rollup."""

    model_config = ConfigDict(extra="forbid")

    scope: str
    collection: str
    total: int
    present: int
    stale: int
    missing: int


class SiteCoverage(BaseModel):
    """A registered site's dataset-coverage rollup (the parity-promotion signal)."""

    model_config = ConfigDict(extra="forbid")

    slug: str
    total: int
    present: int
    missing: int


class AuditReport(BaseModel):
    """The full machine-rendered integrity audit — a pure function of catalog + snapshot."""

    model_config = ConfigDict(extra="forbid")

    reconciled_at: str | None
    total: int
    present: int
    stale: int
    unmaterialized: int
    missing: int
    unobserved: int
    reviewed: int
    collections: list[CollectionAudit] = Field(default_factory=list)
    datasets: list[DatasetState] = Field(default_factory=list)
    sites: list[SiteCoverage] = Field(default_factory=list)


def _site_coverage(
    entries: list[CatalogEntry], snapshot: ObservedSnapshot | None, settings: Settings
) -> list[SiteCoverage]:
    """Per-site present/missing from on-disk resolution (stable; pointer files count as present)."""
    out: list[SiteCoverage] = []
    for slug in sorted(SITES):
        relevant = [e for e in entries if is_relevant(e, slug)]
        present = 0
        for entry in relevant:
            resolved = _resolved_relpaths(entry, slug)
            if resolved and all((settings.data_dir / rel).exists() for rel in resolved):
                present += 1
        out.append(
            SiteCoverage(
                slug=slug, total=len(relevant), present=present, missing=len(relevant) - present
            )
        )
    return out


def build_audit(*, settings: Settings | None = None) -> AuditReport:
    """Reduce the catalog + committed snapshot into the integrity report (no live observation)."""
    settings = settings or get_settings()
    entries = load_entries(settings=settings)
    snapshot = load_observed(settings=settings)
    observed = snapshot.entries if snapshot else {}

    datasets = [
        DatasetState(
            id=e.id, scope=e.scope, collection=_collection(e), state=_state(observed.get(e.id))
        )
        for e in entries
    ]
    datasets.sort(key=lambda d: (d.scope, d.collection, d.id))

    groups: dict[tuple[str, str], list[DatasetState]] = defaultdict(list)
    for d in datasets:
        groups[(d.scope, d.collection)].append(d)
    collections = [
        CollectionAudit(
            scope=scope,
            collection=collection,
            total=len(members),
            present=sum(1 for m in members if m.state in ("present", "unmaterialized")),
            stale=sum(1 for m in members if m.state == "stale"),
            missing=sum(1 for m in members if m.state in ("missing", "unobserved")),
        )
        for (scope, collection), members in sorted(groups.items())
    ]

    def n(state: str) -> int:
        return sum(1 for d in datasets if d.state == state)

    return AuditReport(
        reconciled_at=snapshot.reconciled_at if snapshot else None,
        total=len(datasets),
        present=n("present"),
        stale=n("stale"),
        unmaterialized=n("unmaterialized"),
        missing=n("missing"),
        unobserved=n("unobserved"),
        reviewed=sum(1 for e in entries if e.status == "reviewed"),
        collections=collections,
        datasets=datasets,
        sites=_site_coverage(entries, snapshot, settings),
    )


def render_audit(report: AuditReport) -> str:
    """Render the report as deterministic, markdownlint-clean markdown."""
    asof = report.reconciled_at or "never (run `bosc catalog reconcile`)"
    lines: list[str] = [
        GENERATED,
        "",
        "# Corpus completeness — integrity audit",
        "",
        "The **mechanical** half of the corpus-completeness audit: every dataset registered in "
        "the data catalog (`data/catalog/`) checked for existence and freshness against the "
        "committed reconcile snapshot (`data/catalog/_observed.yaml`). The **substantive** half "
        "— records an authority has *withheld* — stays human-authored in "
        "[`data/extracted/legal/corpus-completeness-audit.md`](../extracted/legal/corpus-completeness-audit.md).",
        "",
        f"Snapshot reconciled: **{asof}**. Regenerate with `bosc catalog audit --apply` "
        "after `bosc catalog reconcile`.",
        "",
        "## Headline",
        "",
        f"- **{report.total}** catalogued datasets — **{report.reviewed}** reviewed.",
        f"- **{report.present}** present and fresh · **{report.stale}** stale · "
        f"**{report.unmaterialized}** LFS pointer (not materialized in this checkout).",
        f"- **{report.missing}** missing (declared files absent) · "
        f"**{report.unobserved}** unobserved (no snapshot record).",
        "",
        "## Coverage by collection",
        "",
        "| scope | collection | datasets | present | stale | missing |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for c in report.collections:
        lines.append(
            f"| {c.scope} | {c.collection} | {c.total} | {c.present} | {c.stale} | {c.missing} |"
        )

    lines += [
        "",
        "## Per-site coverage",
        "",
        "| site | relevant | present | missing |",
        "| --- | --- | --- | --- |",
    ]
    for s in report.sites:
        lines.append(f"| {s.slug} | {s.total} | {s.present} | {s.missing} |")

    gaps = [d for d in report.datasets if d.state in ("stale", "missing", "unobserved")]
    lines += ["", "## Integrity gaps", ""]
    if not gaps:
        lines.append("None — every catalogued dataset is present and within its refresh cadence.")
    else:
        lines += ["| dataset | scope | state |", "| --- | --- | --- |"]
        lines += [f"| `{d.id}` | {d.scope} | {d.state} |" for d in gaps]
    lines.append("")
    return "\n".join(lines)


def audit_drift(*, settings: Settings | None = None) -> str | None:
    """The committed ``COMPLETENESS.md`` relpath if it's missing or out of sync, else ``None``.

    Self-limiting: if the report has never been generated (no committed file) there's nothing to
    drift against, so it returns ``None`` — the gate activates once `bosc catalog audit --apply`
    writes the report the first time.
    """
    settings = settings or get_settings()
    path = settings.data_dir / AUDIT_RELPATH
    if not path.exists():
        return None
    expected = render_audit(build_audit(settings=settings))
    if path.read_text(encoding="utf-8") != expected:
        return AUDIT_RELPATH
    return None


def write_audit(*, settings: Settings | None = None) -> tuple[str, bool]:
    """Render and write ``COMPLETENESS.md``; return its relpath and whether it changed."""
    settings = settings or get_settings()
    path = settings.data_dir / AUDIT_RELPATH
    rendered = render_audit(build_audit(settings=settings))
    changed = not path.exists() or path.read_text(encoding="utf-8") != rendered
    if changed:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
    return AUDIT_RELPATH, changed
